### ISSUE TITLE
Fix Broken Travis

### ISSUE THREAD

**Issue by anant-joshi** [djunicode/canteen-android-app#5]
Android emulator is too old, and is possibly messing up the build. Please check

**Comment by anant-joshi** [comment]
@Ruturaj123 Please add a comment detailing the reason for the issue, and the fix you made.
Then close the issue.

Well done!

**Comment by Ruturaj123** [comment]
The reason for the issue was that Travis doesn't currently support armeabi-v7a API  > 22. That's the reason the emulator was not able to start as previously the Emulator API version was set to 24. 
The emulator API level has been changed to 22 so now it works fine and the build is passing.
